### ISSUE TITLE
Problemas al desplegar en Openshift

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/BackendSI2-IV#90]
No sé qué pasa.
Cada vez que hacemos un push, se paran los servicios en Openshift para desplegar y algo falla en el repo.

Voy a arreglarlo :S

**Comment by JCristobal** [comment]
Creo que el problema no lo generamos nosotros, quizá al hacer un push hay que esperar más de la cuenta a que Openshift despligue... lo digo por lo que nos dice:

[Error 503](http://www.checkupdown.com/status/E503_es.html)
"The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later."

deben de tener el servidor a tope....

**Comment by iblancasa** [comment]
No... por que si reinicio la aplicación desde el panel de control, todo vuelve a funcionar...
¿todo? NO. Me he dado cuenta que los últimos commits no se guardan en OpenShift. He borrado la aplicación y la he vuelto a crear.
Creo que casi lo tengo.

**Comment by JCristobal** [comment]
Eso si es verdad ... cuando estaba desplegada el botón desplegable para elegir la empresa (por ejmplo) no se actualizó en la aplicación de Openshift

**Comment by iblancasa** [comment]
ARREGLADO :D
